/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematecnogas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import servicios.conexion;
import Atxy2k.CustomTextField.RestrictedTextField;

/**
 *
 * @author Wilfredo Serrano
 */
public class Ingreso_Bombas extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection cn = cc.conexion();
    Statement sent;

    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }

    /**
     * Creates new form Ingreso_Bombas
     */
    public Ingreso_Bombas() {
        initComponents();
        asterisco();
        txtIDbomba.setEnabled(false);
        lblFecha.setText(fecha());
        try {
            sent = cn.createStatement();
            String sql = "SELECT * FROM `estado` ";
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = sent.executeQuery(sql);
            comboEstado.addItem("seleccione estado");
            while (rs.next()) {

                this.comboEstado.addItem(rs.getString("estado"));
            }
        } catch (Exception e) {

        }
    }

    public void asterisco() {
        if (txtNumBomba.getText().isEmpty()) {
            asteriscoNumero.setText("*");
        } else {
            asteriscoNumero.setText(" ");
        }
        if (comboEstado.getSelectedItem() == comboEstado.getItemAt(0)) {
            asteriscoEstado.setText("*");
        } else {
            asteriscoEstado.setText(" ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfield_id_bomba3 = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBombas = new javax.swing.JTable();
        txtIDbomba = new javax.swing.JTextField();
        txtNumBomba = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        asteriscoNumero = new javax.swing.JLabel();
        asteriscoEstado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        textfield_id_bomba3.setText("textField2");

        jLabel12.setText("jLabel12");

        jLabel18.setText("Fecha actual:");

        jLabel19.setText("Ingresar en estado:");

        jLabel20.setText("ID_Bomba:");

        jLabel21.setText("Numero de bomba:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bombas");

        jLabel2.setText("ID Bomba:");

        jLabel3.setText("Numero de bomba:");

        jLabel9.setText("Ingresar en estado:");

        btnMostrarTodo.setText("Mostrar todas las bombas");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar nueva bomba");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        tblBombas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblBombas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBombasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBombas);

        txtNumBomba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumBombaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumBombaKeyTyped(evt);
            }
        });

        comboEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboEstadoKeyReleased(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblFecha.setText("dd/MM/YYYY");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        asteriscoNumero.setBackground(new java.awt.Color(255, 0, 0));
        asteriscoNumero.setForeground(new java.awt.Color(255, 0, 0));
        asteriscoNumero.setText("jLabel4");

        asteriscoEstado.setBackground(new java.awt.Color(255, 0, 0));
        asteriscoEstado.setForeground(new java.awt.Color(255, 0, 0));
        asteriscoEstado.setText("jLabel5");

        jLabel4.setText("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMostrarTodo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(122, 122, 122)
                                        .addComponent(lblFecha)
                                        .addGap(17, 17, 17))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtIDbomba, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNumBomba, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(asteriscoNumero)
                                            .addComponent(asteriscoEstado)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDbomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumBomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asteriscoNumero))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asteriscoEstado))
                .addGap(7, 7, 7)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        try {
            if (txtNumBomba.getText().isEmpty() || (comboEstado.getSelectedItem()==comboEstado.getItemAt(0))) {
                JOptionPane.showMessageDialog(null, "No se permiten campos vacios","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                String sql = "INSERT INTO `bombas` (`id_bombas`, `num_bomba`, `fecha_creacion_bomba`, `fecha_actualizacion_bomba`, `estado`) VALUES (NULL, ?, SYSDATE(), SYSDATE(), ?)";
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, txtNumBomba.getText());
                String value = comboEstado.getSelectedItem().toString();
                pst.setString(2, value);
                if (txtNumBomba.getText().length() > 2) {
                        JOptionPane.showMessageDialog(null, "Los campos no pueden tener mas de 2 caracteres","Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
            }}
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "INGRESA TODOS LOS DATOS CORRECTAMENTE","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        String mostrar = "SELECT `id_bombas`, `num_bomba`, `fecha_creacion_bomba`, `fecha_actualizacion_bomba`, `estado` FROM `bombas` WHERE 1";
        String[] titulos = {"ID bomba", "Numero de bomba", "Fecha de creacion de la bomba", "Fecha de actualizacion de la bomba", "Estado de la bomba"};
        String[] Registros = new String[5];
        DefaultTableModel model = new DefaultTableModel(null, titulos);

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                Registros[0] = rs.getString("id_bombas");
                Registros[1] = rs.getString("num_bomba");
                Registros[2] = rs.getString("fecha_creacion_bomba");
                Registros[3] = rs.getString("fecha_actualizacion_bomba");
                Registros[4] = rs.getString("estado");
                model.addRow(Registros);
            }
            tblBombas.setModel(model);
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        panelcentral botonatras = new panelcentral();
        botonatras.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        panelcentral ingresar = new panelcentral();
        ingresar.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE `bombas` SET `id_bombas`= '" + txtIDbomba.getText() + "',`num_bomba`= '" + txtNumBomba.getText() + "',`fecha_actualizacion_bomba`= SYSDATE(),`estado`= '" + comboEstado.getSelectedItem() + "' WHERE `bombas`.`id_bombas`= '" + txtIDbomba.getText() + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO MODIFICADOS");
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "INGRESA TODOS LOS DATOS CORRECTAMENTE","Error",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtIDbomba.setText("");
        txtNumBomba.setText("");
        txtBuscar.setText("");
        comboEstado.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblBombasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBombasMouseClicked
        // TODO add your handling code here:
        int seleccionar = tblBombas.rowAtPoint(evt.getPoint());
        txtIDbomba.setText(String.valueOf(tblBombas.getValueAt(seleccionar, 0)));
        txtNumBomba.setText(String.valueOf(tblBombas.getValueAt(seleccionar, 1)));
        comboEstado.setSelectedItem(String.valueOf(tblBombas.getValueAt(seleccionar, 4)));
    }//GEN-LAST:event_tblBombasMouseClicked

    private void cargar() {
        String mostrar = "SELECT `id_bombas`, `num_bomba`, `fecha_creacion_bomba`, `fecha_actualizacion_bomba`, `estado` FROM `bombas` WHERE `num_bomba` = '" + txtBuscar.getText() + "'" + "OR `id_bombas` LIKE '%" + txtBuscar.getText() + "%'";
        String[] titulos = {"ID bomba", "Numero de bomba", "Fecha de creacion de la bomba", "Fecha de actualizacion de la bomba", "Estado de la bomba"};
        String[] Registros = new String[5];
        DefaultTableModel model = new DefaultTableModel(null, titulos);

        try {
            Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                Registros[0] = rs.getString("id_bombas");
                Registros[1] = rs.getString("num_bomba");
                Registros[2] = rs.getString("fecha_creacion_bomba");
                Registros[3] = rs.getString("fecha_actualizacion_bomba");
                Registros[4] = rs.getString("estado");
                model.addRow(Registros);
            }
            tblBombas.setModel(model);
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        //cargar();
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtNumBombaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumBombaKeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        
        if(evt.getKeyChar()>=33 && evt.getKeyChar()<=47 || evt.getKeyChar()>=58 && evt.getKeyChar()<=255){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten numeros","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNumBombaKeyTyped

    private void txtNumBombaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumBombaKeyReleased
        // TODO add your handling code here:
        asterisco();
    }//GEN-LAST:event_txtNumBombaKeyReleased

    private void comboEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboEstadoKeyReleased
        // TODO add your handling code here:
        asterisco();
    }//GEN-LAST:event_comboEstadoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Bombas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Bombas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Bombas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Bombas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Bombas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asteriscoEstado;
    private javax.swing.JLabel asteriscoNumero;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTable tblBombas;
    private java.awt.TextField textfield_id_bomba3;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIDbomba;
    private javax.swing.JTextField txtNumBomba;
    // End of variables declaration//GEN-END:variables
}
